PrestaShopException: change signature
Type of third constructor parameter $previous was changed from Exception
to Throwable.

We can finally make this change, since PHP5.6 is no longer supported.